services:
  pyspark-notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3